# Generated by Django 4.2.16 on 2025-01-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='transmisson',
            new_name='transmission',
        ),
    ]
