# Generated by Django 4.2.16 on 2025-01-12 14:08

from django.db import migrations, models
import django.db.models.deletion
import user_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=user_app.utils.user_directory_path),
        ),
    ]
